### ISSUE TITLE
Error Running snapchat.py

### ISSUE THREAD

**Issue by luiz-izidoro** [niothiel/snapchat-python#1]
After cloning the repo, using the example script code in the same folder where snapchat.py and changing the username i get this error when running my script based on the example code (that i named sc.py) :
$ python sc.py
Traceback (most recent call last):
  File "sc.py", line 4, in <module>
    s.login('myuser', 'mypassword')
  File "/.../snapchat-python/snapchat.py", line 198, in login
    self.auth_token = result['auth_token']
TypeError: string indices must be integers, not str

**Comment by KrissiBT** [comment]
i am also getting this same error

**Comment by KrissiBT** [comment]
pi@KristoPi ~/marschat/snapchat-python/src $ sudo python send.py
Traceback (most recent call last):
  File "send.py", line 4, in <module>
    s.login('myUser', 'MyPass')
  File "/home/pi/marschat/snapchat-python/src/snapchat.py", line 199, in login
    if 'auth_token' in result:
TypeError: argument of type 'bool' is not iterable

i replaced my actual login info
